### ISSUE TITLE
Data not available from server 

### ISSUE THREAD

**Issue by ChenxiSSS** [svw26/G4Jy#6]
Hi,

Trying to download data with the script got bad request errors.

![image](https://user-images.githubusercontent.com/22267254/104462445-8a3f1e80-55eb-11eb-93e6-1e16c7c03488.png)

![image](https://user-images.githubusercontent.com/22267254/104462477-96c37700-55eb-11eb-9632-338ae82214ed.png)

**Comment by svw26** [comment]
Hiya Chenxi, and @davepallot -- hope you're both doing well.

Dave, it looks like the same kind of error as back in Aug 2020. Please could you restart the server to see whether that fixes it? x

**Comment by davepallot** [comment]
Hi @svw26.
I have restarted the server and everything appears to be back online. Check it and let me know how it goes. 
Regards

**Comment by svw26** [comment]
Thanks, @davepallot. I've checked and it's downloading fine again. @ChenxiSSS, please reopen this issue if it's still not working for yourself. x

**Comment by ChenxiSSS** [comment]
@svw26 It works for me now. Thank you, guys!
