### ISSUE TITLE
Cannot reach the server due to a time-out connection

### ISSUE THREAD

**Issue by svw26** [svw26/G4Jy#7]
Hiya @davepallot, hope you're safe and well!

I saw some emails about changes to the MWA ASVO, and wondered whether it would affect this G4Jy Sample Server. In addition, a user has struggled to download images, and I myself am encountering a 'timed-out' error (Error 522, see screenshot attached) when I try to reach http://mwa-web.icrar.org/gleam_4jy/q/form .

Please could you take a look? 

Best wishes,
Sarah x

<img width="1090" alt="G4Jy_server_Error_522" src="https://user-images.githubusercontent.com/16702076/128918553-2f8c2218-a73e-4e9c-80bb-e41ebcba01d8.png">

**Comment by svw26** [comment]
Hmm, I can't seem to view the screenshot.. so I tried reach the server's webpage again and got the following, if it helps  x
```
Error 522 
Ray ID: 67cb778b497506c3 • 2021-08-10 19:00:26 UTC
Connection timed out
```

**Comment by svw26** [comment]
Hey @gsleap and @nhurleywalker, hope you're both well :)

Perhaps yourselves are better placed to help me with this? I am able to reach http://gleam-vo.icrar.org/gleam_postage/q/form but still not http://mwa-web.icrar.org/gleam_4jy/q/form x

**Comment by gsleap** [comment]
Hi Sarah,

I’m well, and I hope you are the same!

The GLEAM VO services are run by ICRAR/UWA and unfortunately I have no access or visibility on it. I believe Chen Wu used to look after this, but after Chen left ICRAR I’m not sure who it is. Your best bet is to contact Andreas Wicenec at ICRAR UWA, he should be able to point you in the right direction!

Cheers

Greg

**Comment by svw26** [comment]
Whilst the G4Jy Sample Server is being migrated to Astronomy Data Central, all images (cutouts and overlays) associated with the sample can be accessed via the G4Jy repository on Zenodo: https://zenodo.org/communities/g4jy  x
